services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gestion-leads-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - db_net
